### ISSUE TITLE
Intra-word line breaks on facets

### ISSUE THREAD

**Issue by mccalluc** [WGBH/AAPB2#118]
Facet text is being split between characters: really ugly / unreadable. See if there's a CSS fix for this.

**Comment by mccalluc** [comment]
This is coming from blacklight.css:
```css
.facet-values .facet-label {
    -moz-hyphens: auto;
    text-indent: -15px;
    word-break: break-all;
}
```
Disabling that last rule in firebug makes everything look better. Assigning over to @Hammicakes
