### ISSUE TITLE
Bullet points on /projects/permanent-entity

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/AAPB2#874]
The bullet points on the /projects/permanent-entity page are not in alignment with the beginning of each statement in the list.

Done when: bullet points are aligned with the beginning of each statement in the list.

**Comment by mccalluc** [comment]
Ugh: bullet is aligning to the bottom of each block. Here's the CSS that's causing it:
```css
.override-main p:first-child {
    display: inline-block;
}
```
